name: Node.js Package
on:
  push:
    branches: [main]
jobs:
  public-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      # Setup .npmrc file to publish to GitHub Packages
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: pnpm install
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Create Release
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        with:
          path: '.'
        id: package-version
      - name: Create Release Tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          release_name: v${{ steps.package-version.outputs.version }}
          prerelease: false
